tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'github/gh'

brew 'amfora'
brew 'bat'
brew 'catimg'
brew 'composer'
brew 'coreutils'
brew 'cowsay'
brew 'exa'
brew 'fd'
brew 'ffmpeg'
brew 'figlet'
brew 'fortune'
brew 'fzf'
brew 'gh'
brew 'git-delta'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'gping'
brew 'htop'
brew 'httpie'
brew 'httrack'
brew 'hugo'
brew 'imagemagick'
brew 'jq'
brew 'lynx'
brew 'macchina'
brew 'mas'
brew 'mdcat'
brew 'neovim'
brew 'php'
brew 'pinentry-mac'
brew 'rclone'
brew 'ripgrep'
brew 'rust'
brew 'shellcheck'
brew 'tealdeer'
brew 'the_silver_searcher'
brew 'tig'
brew 'trash'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'yt-dlp/taps/yt-dlp'


cask 'docker'




cask 'imageoptim'
cask 'iterm2'
cask 'notion'
cask 'sequel-pro'
cask 'slack'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'

cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-fira-mono'
cask 'font-fira-mono-nerd-font'
cask 'font-inconsolata'
cask 'font-inconsolata-nerd-font'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-ubuntu-mono-nerd-font'
cask 'font-ubuntu-nerd-font'

mas 'DaisyDisk', id: 411643860
mas 'Slack', id: 803453959
mas 'Xcode', id: 497799835
